{% set name = "ngff_zarr" %}
{% set version = "0.34.0" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/n/ngff_zarr/ngff_zarr-{{ version }}.tar.gz
  sha256: cc8a5fcb731e6ce70eabc3112d6502127d7e0e5b532608bc7574f1daaefe019c


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - ngff-zarr = ngff_zarr.cli:main


requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - zarr >=2.13
    - numcodecs >=0.10
    - dask-core
    - importlib_resources
    - typing_extensions
    - platformdirs
    - psutil
    - rich
    - rich-argparse
    - itkwasm
    - itkwasm-downsample

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - ngff_zarr
  commands:
    - pip check

about:
  summary: "NGFF Zarr: Multiscale bioimaging data in Zarr format"
  home: https://github.com/fideus-labs/ngff-zarr
  doc_url: https://ngff-zarr.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt



extra:
  recipe-maintainers:
    - khaled196
    - thewtex
