{% set name = "ngff_zarr" %}
{% set version = "0.45.0" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/n/ngff_zarr/ngff_zarr-{{ version }}.tar.gz
  sha256: c24a9a0a95af9e794bb1d7fc2e49ad1f9e4f8deff2ddac5ff32e9e3260a686f0


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - ngff-zarr = ngff_zarr.cli:main


requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - zarr >=2.13
    - numcodecs >=0.10
    - dask-core >=2026.1.2
    - importlib_resources
    - typing_extensions
    - platformdirs
    - psutil
    - rich
    - rich-argparse
    - itkwasm >=1.0b201
    - itkwasm-downsample

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - ngff_zarr
  commands:
    - pip check

about:
  summary: "NGFF Zarr: Multiscale bioimaging data in Zarr format"
  home: https://github.com/fideus-labs/ngff-zarr
  doc_url: https://ngff-zarr.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt



extra:
  recipe-maintainers:
    - khaled196
    - thewtex
    - vboussot
